# Generated by Django 5.1.1 on 2024-12-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies_tradovate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradovatetoken',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='tradovatetoken',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='tradovatetoken',
            name='refresh_token',
        ),
    ]
